#!/bin/bash
# OpenSentry Camera Node - Quick Setup Script
# Run: chmod +x setup.sh && ./setup.sh

set -e

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║           OpenSentry Camera Node - Quick Setup                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Check for Docker
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Please install Docker first:"
    echo "   curl -fsSL https://get.docker.com | sh"
    exit 1
fi

echo "✅ Docker found"

# Check for camera
echo ""
echo "🎥 Detecting cameras..."
cameras=$(ls /dev/video* 2>/dev/null || true)
if [ -z "$cameras" ]; then
    echo "❌ No cameras found. Please connect a USB webcam."
    exit 1
fi

echo "   Found: $cameras"
default_cam=$(echo "$cameras" | head -n1)

# Check if .env exists
if [ -f .env ]; then
    echo ""
    echo "✅ .env file already exists"
    read -p "   Overwrite with new settings? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "   Keeping existing .env"
        echo ""
        echo "🚀 Starting Camera Node..."
        docker compose up --build -d
        echo ""
        echo "✅ Camera Node is running!"
        echo "   Logs: docker compose logs -f"
        exit 0
    fi
fi

echo ""
echo "📝 Let's configure your Camera Node..."
echo ""

# Get camera name
hostname=$(hostname)
read -p "Camera name [${hostname}]: " camera_name
camera_name=${camera_name:-$hostname}

# Get camera device
read -p "Camera device [${default_cam}]: " camera_device
camera_device=${camera_device:-$default_cam}

# Get secret
echo ""
echo "🔐 Enter the OPENSENTRY_SECRET from your Command Center."
echo "   (Run 'cat .env' on the Command Center to find it)"
echo ""
read -p "OPENSENTRY_SECRET: " secret

if [ -z "$secret" ]; then
    echo "⚠️  No secret entered. Camera will use default credentials."
    echo "   This is less secure but will still work on trusted networks."
fi

# Create .env file
cat > .env << EOF
# OpenSentry Camera Node Configuration
# Generated by setup.sh on $(date)

# Camera identification
CAMERA_NAME=$camera_name
CAMERA_DEVICE=$camera_device

# Security secret (must match Command Center!)
OPENSENTRY_SECRET=$secret
EOF

echo ""
echo "✅ Configuration saved to .env"

# Start the service
echo ""
echo "🚀 Building and starting Camera Node (this may take a few minutes)..."
docker compose up --build -d

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    Setup Complete!                            ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  Camera Name:  $camera_name"
echo "║  Device:       $camera_device"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  Your camera should appear in the Command Center              ║"
echo "║  dashboard within 30 seconds.                                 ║"
echo "╠═══════════════════════════════════════════════════════════════╣"
echo "║  Commands:                                                    ║"
echo "║    View logs:    docker compose logs -f                       ║"
echo "║    Stop:         docker compose down                          ║"
echo "║    Restart:      docker compose restart                       ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
